### ISSUE TITLE
Add filter to select subset of Scenarios

### ISSUE THREAD

**Issue by maurice-hebben** [cryptic-wizard/run-specflow-tests#5]
Request to add a filter argument to be able to select one scenario or a subset of scenarios.

Similar to the nunit3console.exe --filter argument

**Comment by cryptic-wizard** [comment]
Hello Maurice, thanks for your suggestion.  The **filter** argument has been added to v1.3.3 as an optional parameter.  For an example see [dotnet7.yml](https://github.com/cryptic-wizard/run-specflow-tests/blob/main/.github/workflows/dotnet7.yml) or the full list of [optional parameters](https://github.com/marketplace/actions/run-specflow-tests#optional-parameters).  For documentation on the filter expression syntax see the MSDN for [Run selected unit tests](https://learn.microsoft.com/en-us/dotnet/core/testing/selective-unit-tests?pivots=nunit#syntax).
